MapsterMapper/Mapster

src/Fpr/TypeAdapterGlobalSettings.cs, src/Fpr/Utils/ReflectionUtils.cs
Hi,
Thank you for your library. I'm using your library and ran into issue where some classes cannot map. But it should be just copied reference to target.
In my scenario, the class is `DbGeography` which is standard EF type. Even it is class, but it represents primitive type similar to string. 
And every time mapper maps this class, it will throw exception, because this class has no constructor.
The example usage is `TypeAdapterConfig.GlobalSettings.PrimitiveType.Add(typeof (DbGeography));`
=> support custom primitive types

src/Fpr/Adapters/ClassAdapter.cs, src/Fpr/Adapters/CollectionAdapter.cs, src/Fpr/ProjectionConfig.cs, src/Fpr/TypeAdapter.cs, src/Fpr/TypeAdapterConfig.cs, src/Fpr/Utils/ProjectionExpression.cs, src/Fpr/Utils/ReflectionUtils.cs
Hi,
Based on your library, you use `int` as key of record of {TSource + TDestination + has destination flag}. 
Even it is very small chance, but it is possible to have key collision when there are a lot of type mappings.
My solution is using `long`, TSource will use high-order number, TDestination will use low-order number, and destination flag will be positive and negative.
Please review
=> change hash key to long

src/Fpr/Fpr.csproj, src/Fpr/Utils/ProjectionExpression.cs, src/Fpr/Utils/ReflectionUtils.cs
Hi,
This problem comes around Queryable mapping. For EF, `Complex` type is just group of property, it should never be null.
Currently, when we map `src.ContactInfo.Address` to `dest.ContactInfo_Address`, it will generate `ContactInfo_Address = src.ContactInfo == null ? null : src.ContactInfo.Address`.
When we run this query exception occurred, because EF doesn't know how to map `src.ContactInfo` with `null`.
My solution is just check for `Complex` type, and this will generate `ContactInfo_Address = src.ContactInfo.Address` without null checking.
As part of this PR, I also add support for name with underscore when flattening mapping.
Standard EF, for `Complex` type and also navigation type, by default, it will generate name with underscore (`ContactInfo_Address` for my case).
So this fix …
=> support name with underscore + support ComplexType

src/Mapster.Tests/WhenMappingCollections.cs, src/Mapster.Tests/WhenMappingNullablePrimitives.cs, src/Mapster.Tests/WhenMappingPrimitives.cs, src/Mapster/Adapters/ClassAdapter.cs, src/Mapster/Adapters/CollectionAdapter.cs, src/Mapster/Mapster.csproj, src/Mapster/Models/PropertyModel.cs, src/Mapster/Utils/Activator.cs, src/Mapster/Utils/FastObjectFactory.cs, src/Mapster/Utils/ReflectionUtils.cs
Sorry for having more than one topic in single pull request. This is from my code base when I used Mapster for a while.
1. Support more collection types  
Current code base supports only array, List<>, generic interfaces such as IList<>, and ArrayList  
With this pull request, it will support all ICollection<> implementation, such as HashSet<>, ObservableCollection<>.  
And it also supports non-generic interfaces such as IList, ICollection, IEnumerable.
2. Able to set null value to nullable property.  
Current code base will never set null value to nullable property.  
I think Mapper should map all possible values to target.
3. Value types will always be primitive.  
All value types, such as TimeSpan, DateTimeOffset, even custom struct should always be primitive.  
Otherwise, it will …
=> Support more collection types + Able to set null value to nullable property + Value types will always be primitive

README.md
Minor class name typos in README.md around GlobalSettings configuration
=> fix: fix minor class name typos in README.md

README.md, src/Mapster.Tests/Mapster.Tests.csproj, src/Mapster.Tests/WhenExplicitMappingRequired.cs, src/Mapster.Tests/WhenMappingWithExtensionMethods.cs, src/Mapster.Tests/WhenMappingWithImplicitInheritance.cs, src/Mapster/Adapters/ClassAdapter.cs, src/Mapster/MapContext.cs, src/Mapster/TypeAdapter.cs, src/Mapster/TypeAdapterConfig.cs, src/Mapster/TypeAdapterSettings.cs, src/Mapster/project.lock.json
Hi eric, please help review this PR. This PR included your change on extension method. By merging this PR will accept your PR.
I don't fully understand how RequireExplicitMapping works.
From what I understand after your posted issues is RequireExplicitMapping will only apply to Class (not List and Primitive).
Here is scenario.
```
class Parent {
public string Id { get; set; }
public List<Child> Items { get; set; }
}
class Child {
public List<int> Blah { get; set; }
}
var result = TypeAdapter.Adapt<Parent[], List<Parent>>(src);
```
if we have only `TypeAdaptConfig<Parent, Parent>`, we will throw explicit alert on (Child, Child).
But if we have both `TypeAdaptConfig<Parent, Parent>` and `TypeAdaptConfig<Child, Child>`, mapping will be succeeded (we will not validate list and primitives).
=> Explicit mapping

README.md, README.md.orig, src/Mapster.Tests/Mapster.Tests.csproj, src/Mapster.Tests/WhenCreatingConfigInstance.cs, src/Mapster.Tests/WhenMappingWithInstance.cs, src/Mapster.Tests/WhenScanningForRegisters.cs, src/Mapster/IRegister.cs, src/Mapster/Mapster.csproj, src/Mapster/TypeAdapterConfig.cs
1) Static and Instance methods now both have NewConfig() and ForType().  The behavior is not changed in either case.  NewConfig deletes any previous config and ForType enhances any previous config.
2) Internal method Clear(TSource, TDestination) at the static level has been renamed to Remove to make it more similar to typical .Net types where Clear() clears the entire list/dictionary etc...
3) Added Internal Clear() method to clear all types from a configuration.
4) Added assembly scanning that works at both instance and static level.
=> Enhanced Registration for consistency and added assembly scanning

src/Mapster.Tests/Classes/Product.cs, src/Mapster.Tests/WhenProjecting.cs, src/Mapster/Adapters/BaseAdapter.cs, src/Mapster/Adapters/ClassAdapter.cs, src/Mapster/Adapters/CollectionAdapter.cs, src/Mapster/TypeAdapterConfig.cs
if property is null, projection will create empty object rather than null value. This PR will check for null and return default value for projection.
This PR also included more descriptive error message for projection.
=> Hotfix for EF create empty object on projection

src/Mapster.Tests/WhenProjecting.cs, src/Mapster/QueryableExtensions.cs, src/Mapster/TypeAdapterConfig.cs
This is per #39.
I create `ProjectToType` to be used instead of `Project.To`. I don't know this is good name or not, naming thing is hard. We could rename to `ProjectTo` to match with AutoMapper. But in this case, VB call will be `ProjectTo(Of TDest)` instead of `ProjectToType(Of TDest)`.
=> create ProjectToType and obsolete Project.To

src/Mapster.Tests/Mapster.Tests.csproj, src/Mapster.Tests/WhenPassingRuntimeValue.cs, src/Mapster/Adapter.cs, src/Mapster/MapContext.cs, src/Mapster/TypeAdapter.cs
Fix #48 
(Please merge #53 first before reviewing this PR.)
This PR includes
1. Passing run-time values to config
2. New builder pattern which allow us to pass run-time config to Adapt method.
**Example**
On configuration, we can receive run-time value by `MapContext.Current.Parameters`.
```
TypeAdapterConfig<Poco, Dto>.NewConfig()
.Map(dest => dest.CreatedBy,
src => MapContext.Current.Parameters["user"]);
```
To pass run-time value.
```
var dto = poco.BuildAdapter()
.AddParameters("user", this.User.Identity.Name)
.AdaptToType<SimpleDto>();
```
=> Passing Runtime value

src/Mapster.Tests/Mapster.Tests.csproj, src/Mapster.Tests/WhenMappingObjectToDictionary.cs, src/Mapster.Tests/WhenMappingWithDictionary.cs, src/Mapster.Tests/WhenMappingWithFlexibleName.cs, src/Mapster/Adapters/BaseAdapter.cs, src/Mapster/Adapters/BaseClassAdapter.cs, src/Mapster/Adapters/ClassAdapter.cs, src/Mapster/Adapters/CollectionAdapter.cs, src/Mapster/Adapters/DictionaryAdapter.cs, src/Mapster/Adapters/PrimitiveAdapter.cs, src/Mapster/Adapters/RecordTypeAdapter.cs, src/Mapster/Mapster.csproj, src/Mapster/Models/AccessModifier.cs, src/Mapster/Models/ClassModel.cs, src/Mapster/Models/FieldModel.cs, src/Mapster/Models/IMemberModel.cs, src/Mapster/Models/MemberMapping.cs, src/Mapster/Models/ParameterModel.cs, src/Mapster/Models/PropertyModel.cs, src/Mapster/NameMatchingStrategy.cs, src/Mapster/TypeAdapterConfig.cs, src/Mapster/TypeAdapterSetter.cs, src/Mapster/TypeAdapterSettings.cs, src/Mapster/Utils/Extensions.cs, src/Mapster/Utils/ReflectionUtils.cs, src/Mapster/ValueAccessingStrategy.cs
Fix #49 
Pls merge #56 before reviewing this issue.
This PR allows match property names with different convention. Usage is
```
TypeAdapterConfig.GlobalSettings.Default.NameMatchingStrategy(NameMatchingStrategy.Flexible);
```
or
```
TypeAdapterConfig<Foo, Bar>.NewConfig().NameMatchingStrategy(NameMatchingStrategy.Flexible);
```
By defining as flexible, it will allow to match between `PascalCase`, `camelCase`, `lower_case`, and `UPPER_CASE`. This feature is applied to both property mapping & class flattening. And users can defined their own convention (ie, prefix, suffix, replace) by create new NameMatchingStrategy.
=> Flexible name matching

README.md, src/Mapster.Tests/Mapster.Tests.csproj, src/Mapster.Tests/WhenIgnoringConditionally.cs, src/Mapster/Adapters/BaseAdapter.cs, src/Mapster/Adapters/BaseClassAdapter.cs, src/Mapster/Adapters/ClassAdapter.cs, src/Mapster/Models/MemberMapping.cs, src/Mapster/TypeAdapterSetter.cs, src/Mapster/TypeAdapterSettings.cs
Addresses the issue #77.
We need to skip mapping according to some condition, but `Map` with condition sets target to `null`, when condition is met.
I implemented `IgnoreIf` configuration. It ignores mapping the similar way as standard `Ignore`, **but only when condition is met.** This condition takes as arguments both, source and destination objects.
```csharp
TypeAdapterConfig<TSource, TDestination>
.NewConfig()
.IgnoreIf((src, dest) => !string.IsNullOrEmpty(dest.Name), dest => dest.Name);
```
=> IgnoreIf() - conditional ignoring of properties mapping

src/Mapster.Tests/Mapster.Tests.csproj, src/Mapster.Tests/WhenMappingPrivateFieldsAndProperties.cs, src/Mapster/Adapters/ClassAdapter.cs, src/Mapster/Adapters/ClassWithNonPublicMemberAdapter.cs, src/Mapster/Adapters/DictionaryAdapter.cs, src/Mapster/Adapters/RecordTypeAdapter.cs, src/Mapster/Mapster.csproj, src/Mapster/TypeAdapterConfig.cs, src/Mapster/TypeAdapterSetter.cs, src/Mapster/Utils/ReflectionUtils.cs, src/Mapster/ValueAccessingStrategy.cs
Hi,
I just created a private fields/properties accessing strategy (ValueAccessingStrategy.PrivatePropertyOrField), could you help to take a look?
A few things to note:
- I don't include this accessing strategy in default strategy list, since it might be a special case and I think better let users to choose whether to use it or not
- In ClassAdapter.CanMap(), I choose to ignore all types from System namespace since those should have other adapter handle already
- In ClassAdapter.CanInline(), if destination class has any private property, we cannot use inline expression   and have to use block expression (to use Expression.Assign())
- In ClassAdapter.CanInline() and ClassAdapter.GetClassModel(), probably can optimize further by checking whether user specifies …
=> Private fields accessing strategy

src/Mapster.Tests/Mapster.Tests.csproj, src/Mapster.Tests/WhenConvertingFromObjects.cs, src/Mapster/Utils/ReflectionUtils.cs
Casting to primitive types from object may fail in some cases as described in #94
```csharp
object intValAsObject = 123; // Value is Int32
long longVal = (long)intValAsObject; // Throws InvalidCastException
```
I have changed `ReflectionUtils.BuildUnderlyingTypeConvertExpression` method so it always use `Convert` class (instead of casting) when source type is `object` and destination type is primitive.
=> Object to primitive type is always converted using Convert class. Fixes #94

src/Mapster.Tests/Mapster.Tests.csproj, src/Mapster.Tests/WhenMappingArrays.cs, src/Mapster/Adapters/CollectionAdapter.cs
Fixes #99 - "Argument must be single dimensional array type"
Multidimensional arrays are now correctly created. The significant changes are:
- `Expression.NewArrayBounds()` for instantiating array uses overload which takes arguments for every array's rank.
- Expression for copying array's data (`Array.Copy()`) does not use `Expression.ArrayLength()`, but `arrayVar.LongLength` property.
=> Multidimensional arrays are correctly mapped.

src/Mapster.Tests/WhenMappingIEnumerableClass.cs, src/Mapster/Utils/ReflectionUtils.cs
This PR fixes #123. The problem is, that `IEnumerable` classes are not recognized as POCO and thus they are adapted using `PrimitiveAdapter` instead of `ClassAdapter`. I think that removing this condition is safe. If both classes are `IEnumerable`, `CollectionAdapter` will be used - it has higher priority than `ClassAdapter`. And basically, class which implements `IEnumerable` still is just a class and can be mapped as such, and not as a primitive type.
I am not sure what exactly is record type, but I made the same change for `RecordTypeAdapter`.
=> Map to IEnumerable class is done using ClassAdapter instead of PrimitiveAdapter

src/Mapster.Tests/WhenUsingNonDefaultConstructor.cs, src/Mapster/Adapters/BaseAdapter.cs, src/Mapster/Extensions.cs
This PR fixes #117. I tried investigate, why and when the problem was arose. Genesis of this is complicated. In commite 8c8d95e, condition (if destination is not null) was removed from method `CreateBlockExpressionBody` in `BaseAdapter` and `CreateInstantiationExpression` was called always. Where default constructor was calling. (what is incorrect when mapping to target instance without default constructor).
I tried this condition give to back, but tests for mapping to target instance failed.
So
I resolved it with condition for default constructor. If type doesn't have default constructor, destination expression is returning from `CreateInstantiationExpression` method.
=> Fixed #117 - Type does not have a default constructor, when map to target instance

src/Mapster/Adapters/StringAdapter.cs
if type is interface (eg: IEnumerable<int>), count not find ToString method
=> if ToString method is null，Expression.Call throw exception

src/Mapster/Settings/IgnoreDictionary.cs, src/Mapster/TypeAdapterSetter.cs
pass arguments by reference to avoid unnecessary copying
=> use readonly struct and in modifier

src/Mapster.Tests/DynamicTypeGeneratorTests.cs, src/Mapster.Tests/WhenMappingToInterface.cs, src/Mapster/Adapters/BaseAdapter.cs, src/Mapster/Adapters/BaseClassAdapter.cs, src/Mapster/Adapters/DictionaryAdapter.cs, src/Mapster/Mapster.csproj, src/Mapster/Settings/ValueAccessingStrategy.cs, src/Mapster/TypeAdapterSetter.cs, src/Mapster/TypeAdapterSettings.cs, src/Mapster/Utils/DynamicTypeGenerator.cs, src/Mapster/Utils/ReflectionUtils.cs
Closes #220 
Closes #188 
With this changes, Mapster is able to map directly fo interface, without needing the class.
- Mapster will create the class (type) dynamically for every interface it is mapping to. The class is created only once and cached.
- Although the intended use case are simple interfaces with properties only, it supports even interfaces with methods. Calling methods in generated class wil just throw `NotImplementedException`.
- Generics are not supported.
- Indexed properties are not supported.
This (when turned on) will fix the issue #188.
Mapping to interfaces which are not inherited, works out-of-the-box. If interface is inherited, the default behavior stays the same as now - only the properties owned by targe interface are mapped. To map properties from parent …
=> Support map directly to interface

src/Mapster.Tests/WhenUsingAttributeWithNameMatchingStrategy.cs, src/Mapster/Utils/ReflectionUtils.cs
Hi!
This is my first PR. This is supposed to fix: #240 
I had to create a new class to make the test fail. 
If this test runs together with the test on WhenUsingAttribute it wont faild. Maybe because the NameMatchingStrategy setting has no effect after a "Adapt" has ran.
PS: Sorry if my English writing has some mistakes.
=> Fix property name match when using AdaptMember Attribute

src/Mapster.Tool/Mapster.Tool.csproj
=> Include .NET 6.0 as Target Framework for Mapster.Tool

README.md
The sample code for the queryable example was wrong (typo). (Yes, it's a nothing change, but I know "beginner me" would have been thrown by that.)
=> Updated Sample Code in Readme

src/Mapster/TypeAdapterConfig.cs
Hi, guys. We would like to have ability try to compile all mapping configurations in solution and only then fail if something is wrong. We are going to add call Compile method in startup time. Currently, I see only first incorrect mapping configuration and I have to start my solution each time to discover only 1 problem. With this change, I just need to start up my project only one time to get all mapping errors. 
@chaowlert
=> Add ability to compile all mappings and then throw AggregateException

src/Mapster.Tests/WhenMappingToInterface.cs, src/Mapster/Utils/DynamicTypeGenerator.cs, src/Mapster/Utils/ReflectionUtils.cs
Enable `source.Adapt<ITarget>()` always to initialize all properties of the autogenerated class from source (including readonly ones) fixes #374
=> Init read-only properties when mapping with a non-readonly interface fixes #374

src/Mapster.Tests/WhenMappingCollections.cs, src/Mapster/Adapters/CollectionAdapter.cs
I think the CollectionAdapter should respect ConstructUsing so the user can control how the collection is instantiated.
=> Support ConstructUsing in CollectionAdapter

src/Mapster.Tests/WhenMappingToTarget.cs, src/Mapster.Tests/WhenPerformingAfterMapping.cs, src/Mapster.Tests/WhenPerformingBeforeMapping.cs, src/Mapster/Adapters/BaseAdapter.cs, src/Mapster/TypeAdapterSetter.cs
I have noticed that the result object is different from the destination but I have no way to do anything about it. So I thought it would be useful to pass the destination parameter to (before|after)mapping delegates.
It could help with cases like #430
=> Add destination parameter to before and after mapping delegates

src/Mapster.Tests/WhenMappingToConstructorAndPrivateSetters.cs, src/Mapster/Adapters/ClassAdapter.cs
Ensures that if a source property was used in constructor that it will only be reapplied with an explicit resolver.
=> Fixes #385 Private Sets

src/Mapster/TypeAdapterConfig.cs
There's been a few scenarios where I've only had access to a `Type` at runtime and have needed to setup destination mapping rules for these, which isn't possible when there is only a function that takes generic parameters. This PR adds an overload that does the same thing but takes a `Type` function parameter instead of a generic one.
=> Add a non generic overload to ForDestinationType

src/Mapster.Core/Utils/NameHelper.cs
During the mapping phase, I encountered a problem caused by the local culture. The `ToLower` and `ToUpper` methods needed to be changed to `ToLowerInvariant` and `ToUpperInvariant`. I fixed this and the unit tests also ran without issue.
=> The culture problem has been fixed

README.md
This PR mentions the installation using the NuGet CLI from Visual Studio or the alternative for .net core with the dotnet CLI.
Makes it easier to copy and paste the package and full instruction from the readme if you are browsing GitHub.
=> Improve installation instructions in the readme

src/ExpressionDebugger.Console/ExpressionDebugger.Console.csproj, src/ExpressionDebugger.Tests/ExpressionDebugger.Tests.csproj, src/ExpressionDebugger/ExpressionDebugger.csproj, src/ExpressionTranslator/ExpressionTranslator.csproj, src/Mapster.Async.Tests/Mapster.Async.Tests.csproj, src/Mapster.Async/Mapster.Async.csproj, src/Mapster.Core/Mapster.Core.csproj, src/Mapster.DependencyInjection.Tests/Mapster.DependencyInjection.Tests.csproj, src/Mapster.DependencyInjection/Mapster.DependencyInjection.csproj, src/Mapster.EF6/Mapster.EF6.csproj, src/Mapster.EFCore.Tests/Mapster.EFCore.Tests.csproj, src/Mapster.EFCore/Mapster.EFCore.csproj, src/Mapster.Immutable.Tests/Mapster.Immutable.Tests.csproj, src/Mapster.Immutable/Mapster.Immutable.csproj, src/Mapster.JsonNet.Tests/Mapster.JsonNet.Tests.csproj, src/Mapster.JsonNet/Mapster.JsonNet.csproj, src/Mapster.SourceGenerator/Mapster.SourceGenerator.csproj, src/Mapster.Tests/Mapster.Tests.csproj, src/Mapster.Tool/Mapster.Tool.csproj, src/Mapster/Mapster.csproj, src/Sample.AspNetCore/Sample.AspNetCore.csproj, src/Sample.AspNetCore/Startup.cs, src/Sample.CodeGen/Sample.CodeGen.csproj, src/Sample.CodeGen/Startup.cs, src/TemplateTest/TemplateTest.csproj
Do so whilst maintaining the .net 6 TFM using multitargeting thus allowing project to be used by .net6 and .net 7 users and making tests run in both .net 6 and .net 7.
This fixes https://github.com/MapsterMapper/Mapster/issues/475.
It is similar to the PR here https://github.com/MapsterMapper/Mapster/pull/489 which only targets .net 7.
Also fix AddProblemDetails in sample project to use third party extension in .net 6 and built in service in .net 7 (doing this avoids naming collision because the third party library in use and the built in feature in .net 7 both use services.AddProblemDetails() ).
https://andrewlock.net/handling-web-api-exceptions-with-problemdetails-middleware/
=> Add .net 7.0 TFM to all projects (except benchmark)

README.md, src/Mapster.DependencyInjection.Tests/InjectionTest.cs, src/Mapster.DependencyInjection/Mapster.DependencyInjection.csproj, src/Mapster.DependencyInjection/ServiceCollectionExtensions.cs
I think this method is crucial when a developer is trying to migrate from AutoMapper to Mapster
I created a test method for this feature that ran successfully and placed it in the dependency injection tests
=> Add extension method for adding IMapper to service collection

src/ExpressionTranslator/ExpressionTranslator.cs, src/Mapster.Tool/ExtensionOptions.cs, src/Mapster.Tool/MapperOptions.cs, src/Mapster.Tool/ModelOptions.cs, src/Mapster.Tool/Program.cs
Fixes https://github.com/MapsterMapper/Mapster/issues/337 for Mapster.Tool
This allows to add "--nullableDirective" to the options already set within a given csproj file to add an `#nullable enable`, in order to suppress CS8669 warnings that are raised specifically due to generated source files having to add this directive even if a project has `Nullable` enabled.
=> Add options to Mapster.Tool to generate files with #nullable directives

src/Mapster.Tests/WhenUsingIMapFrom.cs, src/Mapster.Tests/WhenUsingIMapFromWrong.cs, src/Mapster/Interfaces/IMapFrom.cs, src/Mapster/Utils/InterfaceDynamicMapper.cs, src/Mapster/Utils/TypeAdapterConfigExtensions.cs
Creating IMapFrom interface
now destination type can inherit from an interface named IMapFrom and they can configure mapping in the same class like this:
```csharp
public class InheritedDestinationModel : IMapFrom<SourceModel>
{
public string Type { get; set; }
public int Value { get; set; }
public void ConfigureMapping(TypeAdapterConfig config)
{
config.NewConfig<SourceModel, InheritedDestinationModel>()
.Map(dest => dest.Value, _ => DesireValues.Number);
}
}
```
and even if you don't implement the method it will automatically create a new config for desire types
ex:
```csharp
public class DestinationModel : IMapFrom<SourceModel>
{
public string Type { get; set; }
}
```
I've added a new extension method to TypeAdapterConfig named ScanInheritedTypes like this:
```csharp …
```
=> Add IMapFrom interface for automatic mapping configuration 

src/Mapster.Tool.Tests/.config/dotnet-tools.json, src/Mapster.Tool.Tests/Mappers/IUserMapper.cs, src/Mapster.Tool.Tests/Mappers/UserMapper.cs, src/Mapster.Tool.Tests/Mapster.Tool.Tests.csproj, src/Mapster.Tool.Tests/TestBase.cs, src/Mapster.Tool.Tests/Usings.cs, src/Mapster.Tool.Tests/WhenMappingWithExistingObjectAndInitProperties.cs, src/Mapster.sln, src/Mapster/Adapters/ClassAdapter.cs, src/Mapster/TypeAdapterSetter.cs, src/Mapster/Utils/ReflectionUtils.cs
I've fixed [#536](https://github.com/MapsterMapper/Mapster/issues/536) and wrote a test that regenerates the exact issue
The test has been passed
I add a method to "ClassAdapter" in [this commit](https://github.com/MapsterMapper/Mapster/commit/f3df57c56841cf6230727f5e2ddf5d73e0c33fa8) to generate reflection code for setting init only properties
The result is like this:
```csharp
public _UserDto MapTo(_User p3, _UserDto p4)
{
if (p3 == null)
{
return null;
}
_UserDto result = p4 ?? new _UserDto();
typeof(_UserDto).GetProperty("Id").SetValue(result, (object)p3.Id);
typeof(_UserDto).GetProperty("Name").SetValue(result, p3.Name);
return result;
}
```
* I did not update the package version in csproj
=> Fix Issues #536 -> Set properties with reflection if destination has init only properties.

src/ExpressionDebugger/ExpressionDebugger.csproj, src/ExpressionTranslator/ExpressionTranslator.csproj, src/Mapster.Async/Mapster.Async.csproj, src/Mapster.Core/Mapster.Core.csproj, src/Mapster.DependencyInjection/Mapster.DependencyInjection.csproj, src/Mapster.EF6/Mapster.EF6.csproj, src/Mapster.EFCore/Mapster.EFCore.csproj, src/Mapster.Immutable/Mapster.Immutable.csproj, src/Mapster.JsonNet/Mapster.JsonNet.csproj, src/Mapster.Tool/Mapster.Tool.csproj, src/Mapster/Mapster.csproj
- Cleanup of conditions in project files to other (old) frameworks, which are not used anymore. All projects in solution targets just .NET 6.
- I also changed element `<TargetFrameworks>` to `<TargetFramework>` everywhere.
=> Remove mentions to old unsupported frameworks from projects

src/Mapster/TypeAdapter.cs
* The source parameter in the Adapt method is now nullable, which allows for null values to be passed in without throwing a null reference exception. This improves the robustness of the code and makes it more defensive against unexpected null values.
@eswann @chaowlert @chaowlert @satano
=> 🐛 fix(TypeAdapter.cs): Make source parameter nullable

src/Mapster.Tool/Program.cs
This PR fixes #580
Examples:
```
typeof(int) => Int
typeof(int?) => Int
typeof(int?[]) => IntArray
typeof(List<string[]>) => StringArrayList
```
=> Generating valid, meaningful method name from destination type

src/Mapster.Tool/Program.cs
This PR fixes #605 
Assembly defines open generic only, so we had to add specialised types used in mappings
Removed removing "Nullable" from type name in order to prevent method/class name collisions
=> Added types used in rules to types hashset

src/Mapster.Tests/WhenPerformingAfterMapping.cs, src/Mapster.Tests/WhenPerformingBeforeMapping.cs, src/Mapster/Adapters/BaseAdapter.cs
This PR fixes #602 
`BeforeMappingFactories` and `AfterMappingFactories` execution order has been reversed to execute methods from base classes first
=> Reversing execution order of Before/AfterMapping

src/Mapster.Tests/WhenSettingMapToTargetWith.cs, src/Mapster/Adapters/BaseAdapter.cs, src/Mapster/Utils/TypeAdapterConfigExtensions.cs
This PR fixes #628 
Added checking if a mapping conversion is defined for desired type
=> Not using shallow copy if mapping rule exists

.github/workflows/dotnet-buildandtest.yml, src/ExpressionDebugger/ExpressionDebugger.csproj, src/ExpressionTranslator/ExpressionTranslator.csproj, src/Mapster.Async.Tests/Mapster.Async.Tests.csproj, src/Mapster.Async/Mapster.Async.csproj, src/Mapster.Core/Mapster.Core.csproj, src/Mapster.DependencyInjection.Tests/Mapster.DependencyInjection.Tests.csproj, src/Mapster.DependencyInjection/Mapster.DependencyInjection.csproj, src/Mapster.EF6/Mapster.EF6.csproj, src/Mapster.EFCore.Tests/Mapster.EFCore.Tests.csproj, src/Mapster.EFCore/Mapster.EFCore.csproj, src/Mapster.Immutable.Tests/Mapster.Immutable.Tests.csproj, src/Mapster.Immutable/Mapster.Immutable.csproj, src/Mapster.JsonNet.Tests/Mapster.JsonNet.Tests.csproj, src/Mapster.JsonNet/Mapster.JsonNet.csproj, src/Mapster.SourceGenerator/Mapster.SourceGenerator.csproj, src/Mapster.Tests/Mapster.Tests.csproj, src/Mapster.Tool.Tests/.config/dotnet-tools.json, src/Mapster.Tool.Tests/Mapster.Tool.Tests.csproj, src/Mapster.Tool/Mapster.Tool.csproj, src/Mapster/Mapster.csproj, src/Sample.AspNetCore/Sample.AspNetCore.csproj, src/Sample.CodeGen/Sample.CodeGen.csproj, src/TemplateTest/TemplateTest.csproj
This pull requests updates all projects to .NET 8.0 (excluding Mapster.Tool.Tests which uses the dotnet-tool install of Mapster.Tool). Closes #630.
=> Add support for .NET 8.0

src/Mapster.Tests/WhenMappingPrimitiveCustomMappingRegression.cs, src/Mapster/Adapters/BaseAdapter.cs, src/Mapster/Adapters/PrimitiveAdapter.cs, src/Mapster/TypeAdapterSetter.cs, src/Mapster/TypeAdapterSettings.cs, src/Mapster/Utils/ReflectionUtils.cs
before:
When you mapping To primitive and string always using [converter logic](https://github.com/MapsterMapper/Mapster/wiki/Data-types#primitives) 
now You can use Custom Conversion logic 
supported:
.MapWith()
.MapToTargetWith()
Supporting primitive type from [source code](https://github.com/MapsterMapper/Mapster/blob/04ac871b55828c3909b6cee4764e6fab40db3983/src/Mapster/Utils/ReflectionUtils.cs#L15) 
> typeof(bool)
>  typeof(short)
>  typeof(int)
>  typeof(long)
>  typeof(float)
>  typeof(double)
>  typeof(decimal)
>  typeof(ushort)
>  typeof(uint)
>  typeof(ulong)
>  typeof(byte)
>  typeof(sbyte)
>  typeof(DateTime)
> +
> typeof(string)
Example:
```
[TestMethod]
public void CustomMappingDateTimeToPrimitive()
{
TypeAdapterConfig<DateTime, long>
.NewConfig()
.MapWith(src => new …
```
=> Add support for primitive types in custom mapping

src/Mapster.Tests/WhenRequiresPropsValidation.cs, src/Mapster.Tests/WhenRequiresPropsValidationWithAdapterConfig.cs, src/Mapster/TypeAdapter.cs
This PR introduces two new extension methods, `ValidateAndAdapt`, for the Mapster library. These methods ensure that all properties in the destination type either exist in the source type or are configured in Mapster. If a property does not exist and is not configured, an exception is thrown.
The PR includes:
- Implementation of `ValidateAndAdapt` methods.
- Test cases that cover different scenarios.
```C#
public static class ReportSelectors
{
#region Selectors
/// <summary>
///     Select WitnessId
/// </summary>
/// <returns>new <see cref="PermissionsToEditProps" />{ WitnessId = report.WitnessId }</returns>
public static readonly Expression<Func<Report, PermissionsToEditProps>> PermissionsToEdit =
e => e.ValidateAndAdapt<Report, PermissionsToEditProps>();
/// <summary>
///     Select …
```
=> Added ValidateAndAdapt Methods for Property Validation

src/Mapster.Tests/WhenMappingNullableEnumRegression.cs, src/Mapster/Adapters/BaseAdapter.cs, src/Mapster/Utils/ExpressionEx.cs
Fix from Isuue #640
It Will Work When Enum Cast to object.  I'm not sure this is the right way.
=> Fix issue #640 - Nullable enum to nullable destination (class or param)

src/Mapster.Core/Attributes/AdaptAsAttribute.cs, src/Mapster.Core/Attributes/AdaptWithAttribute.cs, src/Mapster.Core/Enums/AdaptDirectives.cs, src/Mapster.Core/Utils/RecordTypeIdentityHelper.cs, src/Mapster.Tests/WhenIgnoringConditionally.cs, src/Mapster.Tests/WhenMappingPrivateFieldsAndProperties.cs, src/Mapster.Tests/WhenMappingRecordRegression.cs, src/Mapster/Adapters/ClassAdapter.cs, src/Mapster/Adapters/RecordTypeAdapter.cs, src/Mapster/TypeAdapterSetter.cs, src/Mapster/TypeAdapterSettings.cs, src/Mapster/Utils/ReflectionUtils.cs
Fix Issue:
#501 - _test named OnlyInlineRecordWorked_ (regarding not filling the record with data in the given case)
Add 
1) (InlineExpression is Worked) Field Activation passing Field values not specified in the constructor when creating a new record instance
2) Record Creation on Default Passing Field values not specified in the constructor when creating a new record instance (Activation)
3) A special attribute to support custom classes (structures) that use the [current record definition](https://github.com/MapsterMapper/Mapster/wiki/Data-types#mappable-objects). _description  of spec record at the end of the page_ -
[AdaptWith(AdaptDirectives.DestinationAsRecord)] - **to be confirmed**
Example:
```
[TestMethod]
public void MultiCtorAndInlineRecordWorked()
{
var _sourcePoco = new …
```
=> Fix issue #537 - Step 2 - Add support Extended Record Function + Attribute from support used current record definitions

src/Mapster.Tests/WhenMappingObjectRegression.cs, src/Mapster.Tests/WhenMappingRecordRegression.cs, src/Mapster/TypeAdapter.cs
Fix issue #524
Before:
if Type was packaged into an object:
`object _source = new TSource()
`
Instead of updating with data from TSource, it was converted to the TDestination type
`_source.Adapt(_destination) == _source.Adapt<TDistination>`
=> Fix issue #524 - Add support for working with types packed into an object to the standard adapter

src/Mapster.Tests/WhenMappingToInterface.cs, src/Mapster/Adapters/ReadOnlyInterfaceAdapter.cs
Fixes #755, @andrerav could you please take a look and potentially release a new pre-release version? This regression could've affected many customers (it did us at least) - but the pattern is common.
@DocSvartz CC, I want to verify this doesn't break your code (tests are passing).
=> Fix issue #755 - Regression in interfaces mapping introduced by #649

src/Mapster.Tests/WhenMappingRecordRegression.cs, src/Mapster/Adapters/ReadOnlyInterfaceAdapter.cs
New:
1. Mapping of the interface itself (IActive->IActive) not generate a new implementation from DynamicTypeGenerator.
2. Mapping Derived Interface to Base Interface does not generate a new implementation from DynamicTypeGenerator
=>  Fix issue #755 - Revert to behavior from 7.4.0 and new features

src/Mapster.Tests/WhenIgnoreMapping.cs, src/Mapster.Tests/WhenIgnoringConditionally.cs, src/Mapster.Tests/WhenMappingRecordRegression.cs, src/Mapster/Adapters/BaseClassAdapter.cs, src/Mapster/Adapters/ClassAdapter.cs, src/Mapster/Adapters/ReadOnlyInterfaceAdapter.cs, src/Mapster/Adapters/RecordTypeAdapter.cs
Fix Issue #456 #707 #723
#456 When explicitly set to ignore():
Instance of a class can be created with default values ​​for parameters.
Explicitly set to ignore() not mark param as not matched when config RequireDestinationMemberSource = true,
#707  #723 RecordTypes and Generated Type to Interface received support Ignore() from Ctor parameters
Fix MapToTarget behavior for RecordTypes (Include using Ignore() )
before  from 
```
record TestRecord()
{
public int X { set; get; }
}
record TestRecordY() 
{
public int X { set; get; }
public int Y { set; get; }
}
var source = new TestRecord() { X= 200};
var dest = new TestRecordY() {X = 100, Y= 500}
```
```
var adapt = source.Adapt(dest)  // always adapt == { X=200, Y=0}
```
after 
```
var adapt = source.Adapt(dest)  // adapt == { X=200, Y=500} …
```
=> Improvements to Ignore() processing and Fix MapToTarget behavior for RecordTypes 

src/Mapster.Tests/WhenMappingWithDictionary.cs, src/Mapster/Adapters/DictionaryAdapter.cs, src/Mapster/Compile/CompileArgument.cs
Very basic change to allow for mapping to a dictionary, where the key contains a period.
Without this change, `config.NewConfig<SimplePoco, Dictionary<string, object>>().Map("Key.With.Periods", c => c.Id);` would map to key `"Key"` instead of `"Key.With.Periods"`.
Simply never splitting in the method `CompileArgument.GetDestinationNames` does not make any test fail. However, the method is also referenced from `ReflectionUtils.ShouldMapMember`. It might be that a failing scenario is simply not covered in tests, which is why the option is provided.
=> Allow mapping to a dictionary with a key containing periods

src/Mapster.Tests/WhenMappingMemberNameContainingPeriod.cs, src/Mapster/Utils/ExpressionEx.cs
Alternative to #777, less impactful, keeps `InvokerModel` intact.
Try combining parts if no property or field was found for a single part to allow for mapping properties that contain periods.
From #777:
> The InvokerModel stores the property path as a period joined string. When building the expression for a property path, this string is split on the periods, which makes it impossible to have a property name that contains periods.
>
> Obviously, this is kinda obscure, but I actually ran into this issue. It is possible to have a property name with a period when dynamically building types where pretty much all naming restrictions go out of the window.
=> Feat map members containing periods
